### PR TITLE
add angular 1.x example

### PR DESCRIPTION
**Pull request by manjunatha-d**

### CODE REVIEW

**Comment by manjunatha-d** [comment]
@rwieruch, This PR is for #3.

**Comment by rwieruch** [comment]
Perfect ❤️ I will merge it :) Thank you for this contribution. I will announce the blog post this week on Twitter :)

**Comment by manjunatha-d** [comment]
No problem! :)

I loved your book 'The Road to Learn React' ❤️ Thank you for all the amazing content you post :)

**Comment by rwieruch** [comment]
Thank you so much!

**Pull request merged**
